backend:
  name: github
  repo: mimecine/kiosk-book
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/img"
public_folder: "img"


collections:
  - name: products
    identifier_field: handle
    label: Products
    label_singular: Product
    folder: src/content/products
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Provenance", name: "provenance", widget: "string"}
      - {label: "Materials", name: "materials", widget: "string"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    

