backend:
  name: github
  repo: mimecine/kiosk-book
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/img"
public_folder: "img"
editor:
  preview: false


collections:
  - name: products
    identifier_field: handle
    label: Products
    label_singular: Product
    folder: src/content/products
    create: true
    summary: "{{title}}"
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Provenance", name: "provenance", widget: "string"}
      - {label: "Materials", name: "materials", widget: "string"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    
  - name: pages
    identifier_field: handle
    label: Pages
    label_singular: Page
    folder: src/content/pages
    create: true
    summary: "{{title}}"
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, hint: "Use 'Book:&lt;ChapterTitle&gt;:&lt;PageTitle&gt;' format to create an Essay. Essay will be displayed before the chapter specified."}
      - {label: "Body", name: "body", widget: "markdown", required: true}

